version: '3.5'

services:

  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
volumes:
  postgres:
  pgadmin:
